name: Partial LCOV Code Coverage Report
description: Comments a pull request or a push with the global code coverage
author: Marti Planellas
branding:
  icon: check-square
  color: green
inputs:
  github-token:
    description: Github token
    required: true
  lcov-file:
    description: The location of the lcov.info file
    required: false
  lcov-base:
    description: The location of the lcov file for the base branch
    required: false
  hide-table:
    description: Whether to hide the coverage table or not (defaults to false)
    required: false
  output-file:
    description: The location of the output file
    required: false
runs:
  using: node12
  main: dist/main.js
